/*
 * EEPROM.h
 *
 *  Created on: 01 Aug 2018
 *      Author: wynan
 */

#ifndef DRIVERS_EEPROM_EEPROM_H_
#define DRIVERS_EEPROM_EEPROM_H_


typedef enum EEPROM_List{
	NONE,							// 000
	EE_SILENT_PANIC,					// 001
	EE_AWAY_MODE,						// 002
	EE_MONITOR_MODE,					// 003
	EE_SYSTEM_OFF_MODE,	 				// 004
	EE_SENSOR_LOW_BATTERY,				// 005
	EE_MAINS_ON,						// 006
	EE_MAINS_OFF,						// 007
	EE_BATTERY_OK,						// 008
	EE_BATTERY_LOW,						// 009
	EE_BAT_LOW_HIGH_VALUE,				// 010
	EE_SIGNAL_STRENGTH,					// 011
	EE_PANIC,							// 012
	EE_BY_MESSAGE = 13,
	EE_KEYRING,							// 014
	EE_HEALTH_TEST_PREPAID_MESSAGE,		// 015
	EE_HEALTH_REPORT_DAYS,				// 016
	EE_HEALTH_REPORT_TIME,				// 017
	EE_GPRS_BASE,						// 018
	EE_SMS_BASE,						// 019
	EE_SMS_CELL1,						// 020
	EE_SMS_CELL2,						// 021
	EE_SMS_CELL3,						// 022
	EE_SMS_CELL4,						// 023
	EE_SMS_CELL5,						// 024
	EE_SMS_CELL6,						// 025
	EE_OWN_NUMBER,						// 026
	EE_ZONE1_MESSAGE,					// 027
	EE_ZONE2_MESSAGE,					// 028
	EE_ZONE3_MESSAGE,					// 029
	EE_ZONE4_MESSAGE,					// 030
	EE_ZONE5_MESSAGE,					// 031
	EE_ZONE6_MESSAGE,					// 032
	EE_AWAY_MODE_ZONES_ENABLED,			// 033
	EE_CHIME_MODE_ZONES_ENABLED,		// 034
	EE_CHIME_ANYMODE_ZONES,				// 035
	EE_PROG_PASS,						// 036
	EE_USER_PASS,						// 037
	EE_GPRS_ENABLED,					// 038
	EE_GPRS_DISABLED,					// 039
	EE_SILENT_PANIC_BUZZER_TIME,		// 040
	EE_PREPAID_USSD,					// 041
	EE_SMS_IN_CHIME_MODE,				// 042
	EE_SMS_NOT_IN_CHIME_MODE,			// 043
	EE_APN_NAME,						// 044
	EE_APN_USERNAME,					// 045
	EE_APN_PASSWORD,					// 046
	EE_HTTP_USERNAME,					// 047
	EE_HTTP_PASSWORD,					// 048
	EE_TCP_SERV,						// 049
	EE_TCP_PORT,						// 050
	EE_AT_MESSAGE,						// 051

	EE_CELL1_API = 85,					// 085
	EE_CELL2_API,						// 086
	EE_CELL3_API,						// 087
	EE_CELL4_API,						// 088
	EE_CELL5_API,						// 089
	EE_CELL6_API,						// 090

	EE_SETTING_SEND_SMS_IN_CHIME = 91,
	EE_SETTING_COMMS_GPRS,
	EE_INCOMMING_MESSAGE_NUMBER,

	EE_END
} EEPROM_List;


char * Read_Settings(unsigned int page);

#endif /* DRIVERS_EEPROM_EEPROM_H_ */
